version: '3'
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data: